[NO-REF] chore(META): rewind to the 3.5.0 divergence point
Change-Id: Icb401520ffb05f39c4b79ee58016f8e14e5170b9
Signed-off-by: Yaniv <yaniv@nvidia.com>

diff --git a/init.d/nvmesh_util b/init.d/nvmesh_util
--- a/init.d/nvmesh_util
+++ b/init.d/nvmesh_util
@@ -1,8 +1,5 @@
 #!/bin/bash
 
-# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
-# SPDX-License-Identifier: Apache-2.0
-
 # -*-Shell-script-*-
 #
 # This file contains functions to be used by nvmesh{client,target}
@@ -23,7 +20,7 @@ TRACE_DAEMON_LOCKFILE_DIR=/var/run/nvmesh
 TRACE_DAEMON_DIR=$LOG_DIR/trace_daemon
 TRACE_MAX_BUFF_PER_LOG=25000
 TRACE_MAX_LOGS=4
-DEFAULT_TCP_BASE_PORT_ID=7915	# Corresponds to NVMEIB_IWARP_PORT_ID of
+DEFAULT_TCP_BASE_PORT_ID=7915	# Corresponds to NVMEIB_EXCELERO_IWARP_PORT_ID of
 				# common/nvmeib.h and nvmesh_set_tcp_affinity
 
 DEBUG="Debug"
@@ -143,7 +140,7 @@ decompress_modules_if_needed() {
 		exit 1
 	fi
 
-	kos_to_decompress=`find -L $mdir -name '*.ko.xz.bcp'`
+	kos_to_decompress=`find -L $mdir -name '*.ko.xz'`
 
 	if [ -z "$kos_to_decompress" ]; then
 		return
@@ -151,13 +148,10 @@ decompress_modules_if_needed() {
 
 	should_run_depmod=false
         for ko in $kos_to_decompress; do
-		ko_without_xz=${ko%.xz.bcp}
+		ko_without_xz=${ko%.xz}
 
 		if [ ! -e "$ko_without_xz" ]; then
-			# use the pipe/redirect method which works for ANY suffix.
-			# this avoids the "Filename has an unknown suffix, skipping" error.
-			# this method also keeps the original compressed file, just like --keep.
-			xz -d < "$ko" > "$ko_without_xz"
+			xz -d --keep $ko
         	        if [ $? -ne 0 ]; then
                 	        echo "ERROR: could not decompress $ko with xz"
                         	exit 1
@@ -779,21 +773,6 @@ process_nic_link_layer() {
 	fi
 }
 
-replace_nic_in_list() {
-	# Wrap the list in semicolons to make it easier to replace the nic
-	local nics_str=";$1;"
-	local nic_old="$2"
-	local nic_new="$3"
-
-	nics_str="${nics_str//;$nic_old;/;$nic_new;}"
-
-	# Remove the semicolons from the beginning and end
-	nics_str="${nics_str#;}"
-	nics_str="${nics_str%;}"
-
-	echo "$nics_str"
-}
-
 get_nics_guids() {
 	local nics_str="$CONFIGURED_NICS"
 	local tcp_ifaces_str="$SIW_IFACES"
@@ -839,9 +818,6 @@ get_nics_guids() {
 				orig_el=$element
 				element="$ib_dev:$ib_port"
 				echo "$orig_el is IPoIB Device. Translated to: $element"
-
-				# [NVMESH-7780] Replace the IPoIB name in the nics_ports list
-				nics_ports=$(replace_nic_in_list "$nics_ports" "$orig_el" "$element")
 			else
 				if is_ndev_with_addr_and_mask "$element"; then
 					element=$ret_ndev
@@ -1373,6 +1349,82 @@ loggers_cgroup_init() {
 loggers_cgroup_free() {
 	if [ -n "$LOGGERS_CGROUP" ]; then
 		rm -rf /sys/fs/cgroup/blkio/$LOGGERS_CGROUP
+	fi
+}
+
+is_one_qp_per_recovery_optimized() {
+	if [ ! -z "$2" ]; then
+		specific_dev_flag="-d $2"
+	else
+		specific_dev_flag=""
+	fi
+
+	DB=/etc/nvmesh/Excelero_mlxconfig.db
+
+	$CONFIG_TOOL -e $specific_dev_flag -b $DB q ONE_QP_PER_RECOVERY | awk "
+		/Device type:/ { dev=\$3; };
+		/PCI device:/ {pci=\$3;};
+		/Device:/ { dev_name=\$2; };
+		/QP/ {
+			if ( pci != \"\" ) {
+				device=pci
+			} else {
+				device=dev_name
+			}
+			if ( \$1 == \"ONE_QP_PER_RECOVERY\" ) {
+				current=\$3
+				nextboot=\$4
+			} else {
+				current=\$4
+				nextboot=\$5
+			}
+			if ( ( dev ~ \"ConnectX4\" || dev ~ \"ConnectX5\" || dev ~ \"ConnectX6\" ) && current != \"True(1)\" ) {
+				if ( nextboot != \"True(1)\" ) {
+					printf \"\nERROR: Unoptimized %s configuration for device %s. Performance will be degraded.\", dev, device;
+					print \"\nIn order to fix, issue the command below and power cycle:\";
+					printf \"# $CONFIG_TOOL -d %s -b $DB set ONE_QP_PER_RECOVERY=1\n\n\", device;
+					exit 1;
+				} else {
+					printf \"\nERROR: Unoptimized %s configuration for device %s. Performance will be degraded.\", dev, device;
+					print \"\nPlease power cycle or run mlxfwreset for the new optimized configuration to be digested.\";
+					exit 1;
+				}
+			}
+		}"
+	return $?
+}
+
+check_cx5_64b_doorbell_fix() {
+	if [ "$ofed_version" == "none" ]; then
+		#inbox driver
+		CONFIG_TOOL="mstconfig"
+	else
+		#ofed
+		CONFIG_TOOL="mlxconfig"
+	fi
+
+	if ! which "$CONFIG_TOOL" > /dev/null 2>&1; then
+		echo "WARNING: Missing $CONFIG_TOOL please install the relevant package"
+		return 1
+	fi
+
+	if [ -z "$CONFIGURED_NICS" ]; then
+		#verify qp for all connectX devices on the host
+		is_one_qp_per_recovery_optimized $CONFIG_TOOL
+		if [ "$?" -ne "0" ]; then
+			 exit 1
+		fi
+	else
+		#verify qp for the configured mlx devices only
+		for devport in $mlx_configured_nics; do
+			IFS=':' read -r -a mlx_arr <<< "$devport"
+			dev=${mlx_arr[0]}
+
+			is_one_qp_per_recovery_optimized $CONFIG_TOOL $dev
+			if [ "$?" -ne "0" ]; then
+				exit 1
+			fi
+		done
 	fi
 }
 
